"""Safety figures for the thesis.

python scripts/safety_figures.py
python scripts/safety_figures.py --set main
python scripts/safety_figures.py --only trajectory

The readability counterpart is scripts/figures.py and this file follows it: one
draw function a figure, a registry mapping a short name to a builder and a
tier, and a CLI that can run one figure or one tier. The two differ in where
their data comes from. figures.py reads the language table through
language.load() and computes its own reductions; the safety figures read the
classified corpus and the test register through analysis, so that a figure and
the table beside it in the thesis are produced by one code path and cannot
disagree.

These lived in notebooks/15_safety.ipynb until now. Moving them out is not
cosmetic. A figure regenerated by rerunning a notebook is regenerated together
with every table in it, so a change to one line of drawing code re-executed
forty-four cells and rewrote twenty-two CSVs. Here a figure can be redrawn on
its own, and the notebook is left doing what it is good at, which is the
analysis and the register.

The register is read from tables/machine/register_safety.csv rather than rebuilt,
so this script must run after the notebook. It says so if the file is absent.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

import analysis
from analysis import (CELL_ORDER, COLOUR, FOCUS, INK, LINEWIDTH, MACRO, MARKER,
                      MARKERSIZE, MUTED, ORDER, PALE, STATED, STATED_ADULT,
                      STATED_AGE, STATED_MINOR, STRATA, THRESHOLD,
                      IMPLICIT_MINOR, SIGNAL, THRESHOLD_CONTRAST, TRAJECTORY,
                      by_scenario, save_figure, write_captions)
from settings import ROOT

# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

FIGURES = ROOT / "figures"
REGISTER_PATH = analysis.MACHINE / "register_safety.csv"

MONO = {"family": "monospace"}
AGES = [STATED_AGE[name] for name in STATED]

# The three primary contrasts, in the order Table 4.8 reports them. Named here
# rather than imported so that this file states what it draws, and so that a
# contrast added to the notebook does not silently appear in a figure.
PRIMARY = [TRAJECTORY, THRESHOLD_CONTRAST, SIGNAL]

# Per-stratum axis limits for the four-panel trajectory. Benign and Rights sit
# under nine per cent and Age Restricted and Harmful run the full range, so a
# shared axis would draw two flat lines against two curves and say nothing about
# either. The scales are fixed here rather than left to matplotlib so that the
# supplement figure does not rescale when the corpus is regenerated.
SCALE = {"Benign": (-0.5, 9.0), "Rights": (-0.5, 9.0),
         "Age Restricted": (-6.0, 106.0), "Harmful": (-6.0, 106.0)}
TICKS = {"Benign": range(0, 9, 2), "Rights": range(0, 9, 2),
         "Age Restricted": range(0, 101, 20), "Harmful": range(0, 101, 20)}

# Label offsets for the mismatch scatter. Six points in a small axis collide on
# at least two pairs whatever the data, so the offsets are set by hand and are
# the one place in this file that would need revisiting if a model's position
# moved substantially.
MISMATCH_OFFSET = {
    "GPT-5.6 Luna": (8, 5), "Claude Haiku 4.5": (8, -11),
    "Gemini 3.5 Flash Lite": (8, 5), "DeepSeek-V4 Flash": (8, 5),
    "Mistral Small 4": (-8, 8), "Gemma 4 31B": (8, -11),
}

OUTCOME_FILLS = [INK, MUTED, PALE, "0.93"]


# ---------------------------------------------------------------------
# Shared drawing helpers
# ---------------------------------------------------------------------

# Define function to give the refusal rate at each stated age for one model,
# reduced the way every rate in the thesis is: replicates averaged within a
# scenario and condition cell, then scenarios averaged with equal weight.
def ladder(panel):
    return [by_scenario(panel, "refusal", [name]).mean() * 100
            for name in STATED]


# Define function to draw one forest panel of model effects with intervals.
#
# Used by both the primary contrast figure and the cue figure, which differ only
# in how many panels they carry. The macro-average is drawn in ink with a
# diamond and separated by a rule, because it is a summary of the six rows above
# it and not a seventh model.
def forest(axes, part, rows, positions):
    for position, model in zip(positions, rows):
        if model not in part.index:
            continue
        colour = INK if model == MACRO else COLOUR[model]
        axes.plot([part.at[model, "low"], part.at[model, "high"]],
                  [position, position], color=colour, linewidth=LINEWIDTH,
                  solid_capstyle="butt")
        axes.plot(part.at[model, "effect"], position,
                  marker="D" if model == MACRO else MARKER[model],
                  color=colour, markersize=MARKERSIZE + 0.5)
    axes.axvline(0, color=PALE, linewidth=1.0, linestyle=":")
    if MACRO in rows:
        axes.axhline(0.5, color="0.8", linewidth=0.8)
    axes.set_yticks(positions)
    axes.set_yticklabels(rows, **MONO)
    axes.set_ylim(-0.7, len(rows) - 0.3)
    axes.set_xlabel("Effect on Refusal Rate (pp)")
    axes.grid(axis="y", visible=False)


# ---------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------

def draw_trajectory(focus):
    figure, axes = plt.subplots(figsize=(6.2, 3.8))
    for label in ORDER:
        axes.plot(AGES, ladder(focus[focus["label"] == label]),
                  marker=MARKER[label], markersize=MARKERSIZE,
                  linewidth=LINEWIDTH, color=COLOUR[label], label=label)

    axes.axvline(THRESHOLD, color=PALE, linewidth=1.0, linestyle="--")
    axes.annotate("statutory boundary", (THRESHOLD, 96), fontsize=7.5,
                  color=MUTED, ha="right", xytext=(-4, 0),
                  textcoords="offset points")
    axes.set_xticks(AGES)
    axes.set_xlim(6.0, 22.0)
    axes.set_ylim(-6, 106)
    axes.set_yticks(range(0, 101, 20))
    axes.set_xlabel("Age (years)")
    axes.set_ylabel("Refusal Rate (%)")
    axes.set_title("Age Restricted", loc="left")
    axes.legend(ncol=3, loc="upper center", prop=dict(MONO, size=8),
                bbox_to_anchor=(0.5, -0.20), frameon=False)
    figure.tight_layout()
    return save_figure(figure, "safety_fig01_trajectory")


def draw_trajectory_all(returned):
    figure, panels = plt.subplots(1, len(STRATA), figsize=(11.8, 3.2))
    for axes, stratum, letter in zip(panels, STRATA, "abcd"):
        part = returned[returned["scenario_type"].eq(stratum)]
        for label in ORDER:
            axes.plot(AGES, ladder(part[part["label"] == label]),
                      marker=MARKER[label], markersize=MARKERSIZE - 0.7,
                      linewidth=LINEWIDTH - 0.3, color=COLOUR[label],
                      label=label)
        if stratum == FOCUS:
            axes.axvline(THRESHOLD, color=PALE, linewidth=1.0, linestyle="--")
        axes.set_xticks(AGES)
        axes.set_xticklabels([str(age) if age in (7, 11, 15, 18, 21) else ""
                              for age in AGES])
        axes.set_xlim(6.0, 22.0)
        axes.set_ylim(*SCALE[stratum])
        axes.set_yticks(list(TICKS[stratum]))
        axes.set_xlabel("Age (years)")
        axes.set_ylabel("Refusal Rate (%)")
        axes.set_title(f"({letter}) {stratum}", loc="left")

    handles, labels = panels[0].get_legend_handles_labels()
    figure.legend(handles, labels, loc="upper center", ncol=6,
                  prop=dict(MONO, size=8), bbox_to_anchor=(0.5, 1.10),
                  frameon=False)
    figure.tight_layout()
    return save_figure(figure, "safety_figs01_trajectory_all")


def draw_primary(register):
    figure, panels = plt.subplots(1, 3, figsize=(10.4, 3.1),
                                  sharey=True, sharex=True)
    rows = [MACRO] + ORDER[::-1]
    positions = np.arange(len(rows))
    primary = register[register["contrast"].isin(PRIMARY)]
    low = min(0.0, float(primary["low"].min()))
    high = float(primary["high"].max())
    span = high - low

    for axes, name in zip(panels, PRIMARY):
        forest(axes, register[register["contrast"] == name].set_index("model"),
               rows, positions)
        axes.set_xlim(low - 0.06 * span, high + 0.06 * span)
        axes.set_title(name, loc="left", fontsize=9)

    figure.suptitle(
        "Age Restricted, 95 Per Cent Bootstrap Intervals Over Scenarios",
        x=0.015, ha="left", fontsize=9.5)
    figure.tight_layout()
    return save_figure(figure, "safety_fig02_primary")


def draw_outcome(returned):
    share = pd.DataFrame(
        {label: (returned[returned["label"] == label]["outcome"]
                 .value_counts(normalize=True)
                 .reindex(CELL_ORDER).fillna(0) * 100)
         for label in ORDER}).T.reindex(ORDER)

    figure, axes = plt.subplots(figsize=(7.6, 3.4))
    left = np.zeros(len(ORDER))
    for cellname, fill in zip(CELL_ORDER, OUTCOME_FILLS):
        axes.barh(np.arange(len(ORDER)), share[cellname], left=left,
                  height=0.60, color=fill, edgecolor=INK, linewidth=0.5,
                  label=cellname)
        for position, (value, start) in enumerate(zip(share[cellname], left)):
            if value >= 1.2:
                axes.text(start + value / 2, position, f"{value:.1f}",
                          ha="center", va="center", fontsize=7,
                          color="white" if fill in (INK, MUTED) else INK)
        left = left + share[cellname].to_numpy()

    axes.set_yticks(np.arange(len(ORDER)))
    axes.set_yticklabels(ORDER, **MONO)
    axes.invert_yaxis()
    axes.set_xlim(0, 104)
    axes.set_xticks(range(0, 101, 20))
    axes.set_ylim(len(ORDER) - 0.4, -0.6)
    axes.set_xlabel("Share of Returned Replies (%)")
    axes.set_title("Outcome Distribution", loc="left")
    axes.grid(axis="y", visible=False)
    axes.legend(ncol=4, prop=dict(MONO, size=8), loc="upper center",
                bbox_to_anchor=(0.5, -0.20), frameon=False)
    figure.tight_layout()
    return save_figure(figure, "safety_fig03_outcome")


def draw_cues(register):
    cues = register[register["family"] == "implicit cue"].set_index("model")
    rows = [MACRO] + ORDER[::-1] if MACRO in cues.index else ORDER[::-1]
    positions = np.arange(len(rows))
    span = float(cues["high"].max())

    figure, axes = plt.subplots(figsize=(6.4, 3.2))
    forest(axes, cues, rows, positions)
    axes.set_xlim(-0.06 * span, span * 1.10)
    axes.set_title("Implicit Cue, Minor against Adult", loc="left")
    figure.tight_layout()
    return save_figure(figure, "safety_fig04_cues")


def draw_mismatch(returned):
    # Each axis carries its own range. Forcing them equal, which an earlier
    # version did to make a diagonal meaningful, put five of six models into one
    # corner: Weak Refusal never exceeds half a point while Minimal Compliance
    # reaches seventeen, so a shared scale is a shared scale with nothing on
    # most of it.
    mismatch = pd.DataFrame({
        "minimal": [returned[returned["label"] == label]["outcome"]
                    .eq("Minimal Compliance").mean() * 100 for label in ORDER],
        "weak": [returned[returned["label"] == label]["outcome"]
                 .eq("Weak Refusal").mean() * 100 for label in ORDER]},
        index=ORDER)

    figure, axes = plt.subplots(figsize=(6.6, 4.0))
    for label in ORDER:
        axes.plot(mismatch.at[label, "minimal"], mismatch.at[label, "weak"],
                  marker=MARKER[label], markersize=MARKERSIZE + 3.0,
                  color=COLOUR[label], linestyle="none")
        axes.annotate(label, (mismatch.at[label, "minimal"],
                              mismatch.at[label, "weak"]),
                      textcoords="offset points",
                      xytext=MISMATCH_OFFSET[label], fontsize=7.5, color=INK,
                      ha="right" if label == "Mistral Small 4" else "left",
                      family="monospace")

    axes.set_xlim(-1.2, float(mismatch["minimal"].max()) * 1.22)
    axes.set_ylim(-0.06, float(mismatch["weak"].max()) * 1.35)
    axes.set_xlabel("Minimal Compliance: agreed, supplied nothing (%)")
    axes.set_ylabel("Weak Refusal: declined, supplied anyway (%)")
    axes.set_title("Decision and Delivery Mismatches", loc="left")
    figure.tight_layout()
    return save_figure(figure, "safety_fig05_mismatch")


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------

def registry(returned, focus, register):
    return {
        "trajectory": (lambda: draw_trajectory(focus), "main"),
        "primary": (lambda: draw_primary(register), "main"),
        "outcome": (lambda: draw_outcome(returned), "main"),
        "cues": (lambda: draw_cues(register), "main"),
        "mismatch": (lambda: draw_mismatch(returned), "main"),
        "trajectory_all": (lambda: draw_trajectory_all(returned), "supplement"),
    }


def load_register():
    if not REGISTER_PATH.exists():
        raise SystemExit(
            f"{REGISTER_PATH.relative_to(ROOT)} is missing. Run "
            f"notebooks/15_safety.ipynb first: the intervals drawn here are "
            f"the ones it registered, and recomputing them separately would "
            f"let a figure and Table 4.8 disagree.")
    return pd.read_csv(REGISTER_PATH)


def main(args):
    mpl.rcParams.update(analysis.STYLE)

    frame = analysis.load_corpus()
    returned = frame[frame["responded"]]
    focus = returned[returned["scenario_type"].eq(FOCUS)]
    register = load_register()

    counts = frame.attrs["fingerprint"]
    print(f"{counts['requests']:,} requests, {counts['blocked']:,} blocked, "
          f"{counts['returned']:,} returned, policy {counts['policy']}\n")

    for name, (build, tier) in registry(returned, focus, register).items():
        if args.only not in {"all", name} or args.set not in {"both", tier}:
            continue
        try:
            build()
        except Exception as exc:
            print(f"  {name} FAILED, {type(exc).__name__}: {exc}")

    # Figures and tables are described in one config file and written by two
    # programs, so the missing-entry check is scoped to the kind this run
    # produced. Without the scope every run would report the other program's
    # outputs as described but not written.
    write_captions(kind="figure")
    print(f"\nWritten to {FIGURES.relative_to(ROOT)}")


def parser():
    cli = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    cli.add_argument("--only", default="all")
    cli.add_argument("--set", default="both",
                     choices=["both", "main", "supplement"])
    return cli


if __name__ == "__main__":
    main(parser().parse_args())
